version: "3.3"
services:
  web:
    image: kdetony/imgcloud:0.1
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`tonydev.me`)  
        - traefik.http.routers.web-http.entrypoints=http
        - traefik.http.routers.web-http.middlewares=redirect
        - traefik.http.routers.web-https.rule=Host(`tonydev.me`)
        - traefik.http.routers.web-https.entrypoints=https
        - traefik.http.routers.web-https.tls=true
        - traefik.http.services.web.loadbalancer.server.port=8090
        - traefik.http.middlewares.redirect.redirectscheme.scheme=https

  api:
    image: kdetony/plugapp:0.4
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.api-http.rule=Host(`tonydev.me`)
        - traefik.http.routers.api-http.entrypoints=http
        - traefik.http.routers.api-http.middlewares=redirect
        - traefik.http.routers.api-https.rule=Host(`tonydev.me`)
        - traefik.http.routers.api-https.entrypoints=https
        - traefik.http.routers.api-https.tls=true
        - traefik.http.services.api.loadbalancer.server.port=5000
        - traefik.http.middlewares.redirect.redirectscheme.scheme=https
networks:
  proxy:
    external: true
